backend:
  name: git-gateway
  branch: main
media_folder: "img/uploads"
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/sablona__blog.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "blog"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Datum publikace", name: "date", widget: "datetime"}
      - {label: "Obrázek", name: "foto", widget: "image", required: false }
      - {label: "Perex", name: "perex", widget: "string"}
      - {label: "Obsah", name: "body", widget: "markdown"}
  - name: "aktuality"
    label: "Aktuality"
    folder: "aktuality"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/sablona__blog.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "aktuality"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Datum publikace", name: "date", widget: "datetime"}
      - {label: "Obrázek", name: "foto", widget: "image", required: false }
      - {label: "Perex", name: "perex", widget: "string"}
      - {label: "Obsah", name: "body", widget: "markdown"}
  - name: "galerie"
    label: "Galerie"
    folder: "galerie"
    create: true
    widget: "list"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/sablona__galerie.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "galerie"}
      - {label: "Titulek", name: "title", widget: "string"}
      - {label: "Obrázek", name: "foto", widget: "image", required: false }
      - {label: "Obrázek2", name: "foto2", widget: "", required: false }
      - {label: "Obrázek3", name: "foto3", widget: "image", required: false }
      - {label: "Obrázek4", name: "foto4", widget: "image", required: false }
      - {label: "Obrázek5", name: "foto5", widget: "image", required: false }
  - name: "bohosluzby"
    label: "Bohosluzby"
    folder: "bohosluzby"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/sablona__bohosluzby.njk"}
      - {label: "Tags", name: "tags", widget: "hidden", default: "bohosluzby"}
      - {label: "Rozpis", name: "foto", widget: "image", required: false }
